spring:
  application:
    name : customer-service
  profile:
    active : default

  redis:
    host: localhost
    port: 6379

  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: 123456789

server:
  port: 8082
  
feign:
  client:
    config:
      default:
        connectTimeout: 5000
        readTimeout: 5000

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

logging:
  file : 
    name: C:\Users\Admin\Desktop\logs\customer-service.log