spring:
  application:
    name: mail-service
  profiles:
    active: default
 
  mail:
    host: maildev     
    port: 1025
    username: ""
    password: ""
    properties:
      mail:
        smtp:
          auth: false
          starttls:
            enable: false  

server:
  port: 8084

eureka:
  client:
    service-url:
      defaultZone: http://eureka-service:8761/eureka

logging:
  file:
    name: /logs/mail-service.log   
