spring:
  application:
    name: order-service
  profiles:
    active: default

  redis:
    host: redis-cache     
    port: 6379

  datasource:
    url: jdbc:postgresql://host.docker.internal:5432/postgres   
    username: postgres
    password: 123456789

  rabbitmq:
    host: rabbitmq        
    port: 5672
    username: guest
    password: guest

server:
  port: 8083

feign:
  client:
    config:
      default:
        connectTimeout: 5000
        readTimeout: 5000

eureka:
  client:
    service-url:
      defaultZone: http://eureka-service:8761/eureka  

logging:
  file:
    name: /logs/order-service.log  

management:
  tracing:
    sampling:
      probability: 1.0
  zipkin:
    tracing:
      endpoint: http://zipkin:9411/api/v2/spans       
