spring:
  application:
    name: order-service
  profiles:
    active: default
 
  redis:
    host: localhost
    port: 6379

  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: 123456789

  rabbitmq:
    port: 5672
    host: localhost
    username : guest
    password : guest

server:
  port: 8083

feign:
  client:
    config:
      default:
        connectTimeout: 5000
        readTimeout: 5000

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
      
logging:
  file : 
    name: C:\Users\Admin\Desktop\logs\order-service.log
