spring:
  application:
    name: product-service
  profiles:
    active: default
 
  redis:
    host: localhost
    port: 6379

  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: 123456789

server:
  port: 8081

feign:
  client:
    config:
      default:
        connectTimeout: 5000
        readTimeout: 5000
eureka:
  client:
    service-url:
      defaultZone: http://eureka-service:8761/eureka

logging:
  file : 
    name: C:\Users\Admin\Desktop\logs\product-service.log
  