spring:
  application:
    name: product-service
  profiles:
    active: default
  config:
    import: optional:configserver:http://localhost:8888

  redis:
    host: localhost
    port: 6379

  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: 123456789

server:
  port: 8081

feign:
  client:
    config:
      default:
        connectTimeout: 5000
        readTimeout: 5000
